# Generated by Django 2.0.13 on 2020-03-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='imagefile'),
        ),
    ]
